version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/share/nginx/html:ro
    networks:
      - adbid-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add PostgreSQL for future backend
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: adbid
  #     POSTGRES_USER: adbid
  #     POSTGRES_PASSWORD: localpassword
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - adbid-network

networks:
  adbid-network:
    driver: bridge

volumes:
  postgres_data: